hooks:
  all:
    pre:
      - type: oidc
        provider: aws
        role_arn: "arn:aws:iam::975050186482:role/terrateam"
access_control:
  enabled: true
  policies:
    - tag_query: ''
      apply: ['team:devops']
